# Dispatchable workflow that can be run to cleanup stale images from the GCP Artifact Registry.

name: Cleanup Stale GCP Artifact Registry Images

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry Run Flag (1 = true, 0 = false)'     
        required: true
        default: '1'

env:
  GKE_ZONE: europe-west2-c
  GKE_REGION: europe-west2

jobs:

  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: ${{ secrets.GC_PROJECT_ID }}
          token_format: 'access_token'
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_GITHUB_WIP }}
          service_account: ${{ secrets.GC_AR_SERVICE_ACCOUNT }}
          access_token_lifetime: '60s'
      
      - uses: 'docker/login-action@v1'
        name: 'Docker login'
        with:
          registry: '${{ env.GKE_REGION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      
      - name: Cleanup stale Artifact Registry images 
        run: |
          chmod +x ./scripts/clear_stale_artifact_images.sh
          ./scripts/clear_stale_artifact_images.sh ${{ github.event.inputs.dryRun }}
      