name: db-migrate

on:
  push:
    branches: [ 'main' ]
    paths:
      - cloud-sql/migrations/**

  workflow_dispatch:

jobs:

  migration:

    name: Migrate Up
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20' ]

    steps:

      - uses: actions/checkout@v2

      - name: Setup environment
        working-directory: ./cloud-sql/migrations
        run: |
          touch .env
          echo "DB_ROOT_CONNSTRING=${{ secrets.DB_ROOT_CONNSTRING }}" >> $GITHUB_ENV
          echo "${{ secrets.DB_ROOT_CONNSTRING }}" >> .env

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Display Go version
        run: go version

      - name: Install Go dependencies
        working-directory: ./cloud-sql/migrations
        run: |
          go get .

      - name: Login on GC SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GC_SERVICE_ACCOUNT }}
          instance: ${{ secrets.GC_DB_INSTANCE }}

      - name: Run migrations up
        working-directory: ./cloud-sql/migrations
        run: go run main.go